### ISSUE TITLE
Terraform variable monitoring_enabled usage

### ISSUE THREAD

**Issue by Simranpal** [SUSE/ha-sap-terraform-deployments#165]
I set the variable monitoring_enabled to false in my terraform.tfvars and still terraform continue to create the monitoring module, Also asking to specify "monitoring_srv_ip"

**Comment by MalloZup** [comment]
` monitoring_enabled` variable is for disabling the installation of the exporters in the `hana_node` hosts.

It will not disable  the monitoring module. If you don't want to use the monitoring module you need to remove it from your `main.tf` ( this is the standard terraform approach).


I think we should perhaps improve the doc and move it outside from `libvirt` since we will have `monitoring` for all provider.
Currently the doc is anchored in libvirt.

**Comment by MalloZup** [comment]
this is done.. We are solving that issue by a new rfc on confluence closing
