### ISSUE TITLE
Set a default Grafana user dashboard

### ISSUE THREAD

**Issue by stefanotorresi** [SUSE/ha-sap-terraform-deployments#227]
It would be nice to have the main dashboard open up automatically when browsing the monitoring server.
This is not supported by provisioning yet, but can be accomplished by performing a PUT request to the Grafana HTTP API as follows:

```
curl -X PUT \
    -H 'X-Grafana-Org-Id: 1' \
    -H 'Content-Type: application/json' \
    -d '{"homeDashboardId": 1}' \ 
    $MONITORING_IP/api/user/preferences
```

I guess we could use the salt http module in [salt/monitoring/init.sls](https://github.com/SUSE/ha-sap-terraform-deployments/blob/05c61526e17ba2edfe3b7f2d5630795d3a252ad9/salt/monitoring/init.sls)?

**Comment by MalloZup** [comment]
@stefanotorresi  I think personally setting a default perhaps one day grafana will make this possible somehow by provisioning. Imho I'm also ok to add this kind of feature. But it has a little cost since we are doing a post to an API that could perhaps change and fail. So imho for so little avantage. we can still wait. Call me a minimalist pessimist :grin:

**Comment by MalloZup** [comment]
@stefanotorresi imho retrospectively do we need this? I mean imho there is no real default dashboard, since the are several use-case and focuses (hana, netweaver, cluster) etc. 

Imho we can close this

**Comment by stefanotorresi** [comment]
I don't know, I think we should show the multicluster overview by default. @diegoakechi what do you think about this? Do you think it's desirable?

**Comment by MalloZup** [comment]
@diegoakechi  imho can we close this, or we add a default. I personally don't like the `curl` maybe grafana new version has this feature.

**Comment by MalloZup** [comment]
@stefanotorresi  I do think settting a dashboard default is not technically right.

Since we do have rpm packages, we could set X dashboard default and maybe this is missing because the customer didn't install the `ha-dashboard` .. 

I would in favor to close it , since I don't see the advantage of putting effort to fix this.

**Comment by stefanotorresi** [comment]
how is this tech debt? it's not even implemented! 😁 
yeah, I guess we can close it.

**Comment by MalloZup** [comment]
thx for your understanding and let focus on things which will give value.. hopefully :grin:
