### ISSUE TITLE
Allow to provision multiple ISCSI server

### ISSUE THREAD

**Issue by stefanotorresi** [SUSE/ha-sap-terraform-deployments#293]
Currently, the ISCSI server is a single point of failure. Me, @arbulu89 and @gao-yan discussed this at length in a voice call and concluded that it's probably a good idea to provide a pool of ISCSI hosts, still with partitioned devices for each cluster.

**Comment by gao-yan** [comment]
Just to clarify, a single sbd device is not a single point of failure of "cluster". Because a failure of sbd device only disables the ability of fencing, it doesn't prevent cluster from serving. Of course with failed sbd device, cluster is under "degraded" state, which should be resolved as early as possible, in case any needs of fencing occur soon.

OTOH, providing redundancy of sbd by using 3 sbd devices would make the ability of fencing more robust, which is definitely better.

Besides, each sbd device (partition) is better only used by one cluster, so that it provides isolation between clusters, although they still could share a same iSCISI server/target/LUN/disk.

**Comment by MalloZup** [comment]
I do think @arbulu89  has fixed.

all, and @stefanotorresi  in case contrary feel free to reopen

**Comment by arbulu89** [comment]
This feature is not still provided.

**Comment by arbulu89** [comment]
@stefanotorresi I'm closing this ticket, as this feature has not been really asked by any user.
If this changes in the future we will open a dedicated ticket.
