### ISSUE TITLE
Sbd panels shows old devices data

### ISSUE THREAD

**Issue by arbulu89** [SUSE/ha-sap-terraform-deployments#298]
I have found that the sbd panel shows all devices data that are not anymore in the cluster.
![image](https://user-images.githubusercontent.com/36370954/70695437-9b677e80-1cb9-11ea-9750-4af65bac6b85.png)
In this example, the disk `/deb/sda` data was created by error initially, but after updating the sbd configuration file, the metric data is still shown.
Is this the behaviour we want? Personally, I would only show the currently existing devices status in the dashboard, we can always go back in time if it's needed to find previous errors.

How to reproduce:
Edit the file /etc/sysconfig/sbd and add any new entry to SBD_DEVICE. After the metric is retrieved, remove this entry from the configuration file

Edit: After a while (more than 5 minutes) the old entry is removed... I guess that we can live with this, right? If you think so just close the ticket

**Comment by stefanotorresi** [comment]
I've seen this kind of delay happen for other metrics too, so we must be doing something wrong either with the collector or with the queries.

Some further investigation is due.

**Comment by stefanotorresi** [comment]
So, apparently this was an upstream bug (prometheus/prometheus#398) which has been fixed in Prometheus 2.x, but we can't take advantage of the new staleness logic unless we drop the timestamps from all the metrics exported by `ha_cluster_exporter`, which adds timestamp by default.
This means that we currently fall back to the old staleness logic, which simply marks metric as stale when they don't appear in scrapes for 5 minutes.

**Comment by arbulu89** [comment]
@stefanotorresi So, as far I understand, we will only have this "incorrect" report during 5 minutes, right?

**Comment by stefanotorresi** [comment]
yes, which admittedly is a problem, because 5 minutes is quite a long time for a monitoring system with alerts.
