### ISSUE TITLE
Netweaver Cluster is wrongly configured on Prometheus

### ISSUE THREAD

**Issue by diegoakechi** [SUSE/ha-sap-terraform-deployments#301]
All the 4 machines for the Netweaver cluster are being included as part of the netweaver-cluster job inside Prometheus configuration. 

The job_name is used to group the cluster nodes from the monitoring perspective.

As on Netweaver, only the ERS and ASCS hosts are part and maintained by pacemaker cluster, having the PAS and AAS instances inside the configuration causes distortion on the metrics/dashboards. 

The ERS and ASCS should be included as part of the job_name clusters, and the AAS and PAS could be included in a second job_name, called as `netweaver-appservers` as a suggestion.

**Comment by stefanotorresi** [comment]
I don't think we need an additional `job_name`, because this bears no semantic in relation to Pacemaker. On the contrary, it generically identifies a set of targets, and not all of these are `ha_cluster_exporter` instances. In the case of Netweaver, we'll have 4 instances of `node_exporter` and just 2 of `ha_cluster_exporter`.
What we need to change is to only set the `ha_cluster_exporter` targets for the nodes where it actually has to run.
