### ISSUE TITLE
Merge 'qa_mode' and 'devel_mode' variable

### ISSUE THREAD

**Issue by ldevulder** [SUSE/ha-sap-terraform-deployments#362]
I saw that there is 2 variables which look very similar: `qa_mode` and `devel_mode`. I think that we could try to merge them and use only one, WDYT?

**Comment by MalloZup** [comment]
hi @ldevulder  no they are not the same. 

The develmode variable is used to install the latest repositories etc, but everything will activated modules scc etc.

Where the Qa-mode you know it already.

I'm closing this isssue since they can't be merged togheter, they are 2 different use-cases. For any other question feel free to ping. Thx!
