### ISSUE TITLE
[QUESTION] How can I set the number of Netweaver AS ?

### ISSUE THREAD

**Issue by picoroma** [SUSE/ha-sap-terraform-deployments#403]
I'm testing the complete deployment with HA Hana Cluster and Netweaver.
Seems that  the deploy creates 4 AS.
How can set this number of servers ?
For example if I want only one AS or two?
P.

**Comment by diegoakechi** [comment]
@picoroma Currently it is not configurable on the project, but you can adapt the `main.tf` increasing or reducing the number of hosts:

https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/aws/main.tf#L3

When doing that, it is important to notice that you need to adapt the netweaver pillar file mapping the nodes where you want each service to be installed.

https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/netweaver_node/files/pillar/netweaver.sls#L59

We have never tested that since we follow mostly SUSE best practices for Clustering, but let us know how does it go.

**Comment by MalloZup** [comment]
@picoroma does it solve your question? can we close this issue? TIA

**Comment by MalloZup** [comment]
closing as solved for any comments or if you thinkg is not solved feel free to re-open thx!
