### ISSUE TITLE
New NW dashboard process list colors

### ISSUE THREAD

**Issue by arbulu89** [SUSE/ha-sap-terraform-deployments#420]
I have noticed that the process list colors `gray` state is painted with green color:

![image](https://user-images.githubusercontent.com/36370954/78775914-eb680080-798e-11ea-8627-fa38349ff7e7.png)

**Comment by stefanotorresi** [comment]
Yeah, this is something I have wrestled with already: there is no way to make the threshold match all the colours, because Grafana only supports 2 increasing thresholds, but the SAP colour codes are 4 and they are not in order (of course :man_facepalming: ), so I couldn't get all of this to quite match: YELLOW and RED should match respectively with `3,4` as thresholds, but GRAY will not because it's code `1`, so it's lower than GREEN which is `2`.

Feel free to suggest another approach.

**Comment by stefanotorresi** [comment]
fixed by #454
