### ISSUE TITLE
Refactoring: consider to remove monitoring image

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#432]
In order to remove complexity, remove the following variable:

https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/libvirt/variables.tf#L109

We never used it specifically. ( Even if it is a small step, is a less small step toward complexity)

@stefanotorresi  I personally never used the fact to create a different os for grafana and prometheus and I think is not needed.

**Comment by diegoakechi** [comment]
@MalloZup We don't do this because we have "super powers"  as developers, but considering a real customer deployment, where they pay subscriptions, they will most probably use SLES for SAP images for the HANA deployment and plain SLES for the monitoring machine, since it has no specific need for SLES for SAP, therefore this variable exists. Also, another possibility is that you want to run your monitoring on the latest SLES version, while your SAP environment needs to stick with some older and stable SLE version (this is a very common practice on sysadm of mission critical applications). In that scenario, this variable is also important.

We could maybe, complement the description of the variable with some of these details.

**Comment by MalloZup** [comment]
ok sounds a enough good explantaintion closing
