### ISSUE TITLE
Support of QA mode is missing in DRBD module

### ISSUE THREAD

**Issue by ldevulder** [SUSE/ha-sap-terraform-deployments#435]
QA mode is not supported in DRBD module like in the HANA module (on GCP, not tested on Azure but should be the same).

NetWeaver module should have the same isssue.

This can cause issue when we try to test image of a non-release OS version, for example 15-SP2 in my case. On old 15-SP2 image tries to do an update of the OS and this fails because of dependency issues (and that could happens on dev version, and that's "normal").
The output of the log files also contains colors (the salt part mainly) and that more difficult to read/analyze in that case.

So, please (re)add the support of QA mode for new modules :-)

**Comment by arbulu89** [comment]
@ldevulder The `QA` mode was not set initially by purpose, as we didn't have any need to run QA specific operations in DRBD and NetWeaver.
If we have this new requirement now, obviously we can add this flag.
As soon as the flag is added, the colors issue will be solved.

**Comment by Simranpal** [comment]
I added the QA mode support for nw and drbd: https://github.com/SUSE/ha-sap-terraform-deployments/pull/444

**Comment by MalloZup** [comment]
this was fixed since https://github.com/SUSE/ha-sap-terraform-deployments/blob/16b27530f03552448d3610b598a8602e8b04f747/generic_modules/common_variables/variables.tf#L75 is a generic module which module such drbd and others take from
see
https://github.com/SUSE/ha-sap-terraform-deployments/blob/16b27530f03552448d3610b598a8602e8b04f747/gcp/modules/drbd_node/salt_provisioner.tf#L48

thx! closing
