### ISSUE TITLE
get_os_image module returned error during tf plan

### ISSUE THREAD

**Issue by weikiat8** [SUSE/ha-sap-terraform-deployments#487]
### Terraform Version
```
Terraform v0.12.19
+ provider.aws v2.63.0
+ provider.null v2.1.2
```
### Behavior
When specify ami_id for HANA, iSCSI, monitoring, have to manually comment out the get_os_image module to prevent it from running otherwise it will try to search and returned 0. Example:
```
/*
module "get_os_image" {
  source   = "../../modules/get_os_image"
  os_image = var.os_image
  os_owner = var.os_owner
}
*/

## EC2 HANA Instance
resource "aws_instance" "clusternodes" {
  count                       = var.hana_count
  ami                         = var.os_image
```
Once commented out the tf plan runs fine.
### Debug Output
```
Error: Your query returned no results. Please change your search criteria and try again.

  on modules/get_os_image/main.tf line 2, in data "aws_ami" "image":
   2: data "aws_ami" "image" {

```
### Steps to reproduce
Provide ami-id, with below example "suse-sles-sap-12-sp3-v20191112-hvm-ssd-x86_64" and Terraform Plan
```
# Custom AMI for nodes
hana_os_image = "ami-0dd28300839103b16"
# Or use a pattern to find the image
```

**Comment by arbulu89** [comment]
@weikiat8 Thanks for reporting! We will have a look

**Comment by arbulu89** [comment]
Hi @weikiat8 ,
I have been checking this issue and I know what's going on.

The thing is that to retrieve the images using the filters, we need to use a pattern for the name, and the owner of the ami.

The case is that the ami you are using (I found out that `ami-0ab2953d28a3069fe` is for `suse-sles-sap-12-sp3-v20191112-hvm-ssd-x86_64`, I have not found the one you posted ) has a different owner, `679593333241`.

So to make it work you would need to set:
```
hana_os_image = "ami-0dd28300839103b16"
hana_os_owner = "679593333241"
```
With this configuration you shouldn't have this problem.

Anyway, I see that this is quite annoying, because when you know the ami id, you wouldn't need to worry about the owner.

We will try to change the current code, to only use the filters if the ami id is no `ami-*`, so in this 2nd case we wouldn't need to set the owner value.

**Comment by arbulu89** [comment]
@ldevulder As you implemented this, I have a question for you.
Do you see any problem if we change `aws` `get_os_image` module to do the next:
- If `os_image` is something like `ami-xx`, use this ami directly, without running the `data "aws_ami"`. We could do this using the `count` option. In this case, the owner variable wouldn't be used.
- Otherwise, do what we do know, with the image and owner.

What do you think? This implementation would have the benefit that the user if he has the `ami` id, he doesn't need the owner number. In the other hand, we cannot verify if the ami exists, as it would be treated as a normal string.

**Comment by arbulu89** [comment]
Closing this as it got stalled
