### ISSUE TITLE
Errors on .SAR Extract and install.

### ISSUE THREAD

**Issue by stephenmogg** [SUSE/ha-sap-terraform-deployments#555]
Using AWS.
When using SAPCAR/and .SAR files....
WIth:
hana_archive_file = "IMDB_SERVER100_122_21-10009569.SAR"
hana_sapcar_exe = "SAPCAR_1110-80000935-linux.EXE"
hana_extract_dir = "/sapmedia/HDBSERVER"
HANA does not get installed results in 9 errors in Salt Log

With exactly the same setup and hana_extract_dir **not set** ...
hana_archive_file = "IMDB_SERVER100_122_21-10009569.SAR"
hana_sapcar_exe = "SAPCAR_1110-80000935-linux.EXE"
#hana_extract_dir = "/sapmedia/HDBSERVER"

Only 2 errors, but HANA is installed and cluster is set up.

Live environment / logs available.

I've tried these settings with ready extracted media and it works fine, no errors.
Will try with HANA v2.

**Comment by stephenmogg** [comment]
Retesting.

**Comment by Simranpal** [comment]
Hi @stephenmogg could you provide the logs, or error states. We changed recently the default `hana_extract_dir` because it may not be possible to extract to NFS share (which is mounted on same directory /sapmedia) Also what kind of hana scenario are you trying, with/without monitoring? as monitoring needs additional packages, which will not be part of IMDB_SERVER...SAR file
