### ISSUE TITLE
Hana System Replication 

### ISSUE THREAD

**Issue by picoroma** [SUSE/ha-sap-terraform-deployments#602]
Hi!
I tryied to deploy an HANA CLUSTER with 2 nodes.
I have configured the active/active to false with parameter:

# hana_active_active = false

But The results is an Active/Active HANA cluster, anyway.
Seems that this Variable was not recognized by the script.
How can I deploy a HANA CLUSTER with Primary Node Active and Secondary Node NOT Active - But in sync with primary one?
regards
P

**Comment by arbulu89** [comment]
@picoroma I don't know if the `active/active` thing is what you think it is hehe
The `active/active` of our deployment means that both primary and secondary have read capabilities.

In a normal scenario, we could just read from the primary. This is what this variables enables.
I think what you comment (`secondary` not active) is not implemented.

**Comment by Simranpal** [comment]
@picoroma do you mean changing the hana system replication behavior? like changing the hana replication mode or operation modes?

**Comment by picoroma** [comment]
Hi!
I mean a deployment where the 1st node (Primary) is simply in "sync" with a Secondary node with HSR (Hana System Replication).
The replica is called "Synchronous" (Full).
As described here:
https://wiki.scn.sap.com/wiki/display/SAPHANA/Replication+modes

The secondary node is not Active - It caN BE ELIGIBLE TO PRIMARY IN CASE OF FAIL on primary node.

**Comment by Simranpal** [comment]
Hi @picoroma I think you are referring to the HANA Operation modes and looking to have it `logreplay`. 
Hana ACTIVE/ACTIVE mode works in the `logreplay_readaccess` Operation mode.

you can check if active/active is enabled via: `hdbnsutil -sr_state | grep "operation mode"`
If its enabled, it will show - `operation mode: logreplay_readaccess`
otherwise, `logreplay`

https://help.sap.com/viewer/6b94445c94ae495c83a19646e7c3fd56/2.0.04/en-US/627bd11e86c84ec2b9fcdf585d24011c.html

How did you check the active/active status?
If you have set terraform variable `hana_active_active = false`, and it does not set the operation mode correctly, then it is an issue we can check. Let us know, if this configuration does not work.
If you want to simply change the Hana Replication mode, you can change it also via the hana pillar, by default its `sync`

https://github.com/SUSE/ha-sap-terraform-deployments/blob/16b27530f03552448d3610b598a8602e8b04f747/pillar_examples/automatic/hana/hana.sls#L80

**Comment by arbulu89** [comment]
Issue fixed in https://github.com/SUSE/ha-sap-terraform-deployments/pull/638
