### ISSUE TITLE
Missing Travis check for Salt files

### ISSUE THREAD

**Issue by ricardobranco777** [SUSE/ha-sap-terraform-deployments#66]
Now that we have lots of Salt files around it would be nice to have a Travis check for these.

**Comment by MalloZup** [comment]
@ricardobranco777  you can take inspiration from this

https://github.com/SUSE/saphanabootstrap-formula/pull/44

**Comment by MalloZup** [comment]
https://github.com/SUSE/habootstrap-formula/pulls

**Comment by MalloZup** [comment]
@ricardobranco777 both PR were merged. as you see you can create grains on the fly etc. Feel free to to take inspiration from them. I think this repo as less priority then the other formulas because with this repo one can test directly where the other formulas where trickier to tests.

If you want to take ownership to solving this pb for ha-sap-terraform, let me know i will give you some pointers, if needed :rocket: 

I currenlty plan to do other things. :+1:

**Comment by diegoakechi** [comment]
@ricardobranco777  We have salt-lint now being executed, so I will close this as solved by the https://github.com/SUSE/ha-sap-terraform-deployments/pull/225
