### ISSUE TITLE
iscsi-formula should be only installed in the iscsi server machine

### ISSUE THREAD

**Issue by stefanotorresi** [SUSE/ha-sap-terraform-deployments#725]
Currently, the iscsi-formula is installed in all the machines, which is not actually needed.

We should change the salt `os_setup` state so that this is cleaned up.

**Comment by stefanotorresi** [comment]
being addressed in #731

**Comment by melzer-b1** [comment]
We found a suitable solution by adding a jinja conditional in os_setup. We also tried another solution by moving the iscsi-formula to iscsi_srv. But this solution was more complex because it needed another salt run in deployment to use iscsi-formula. It was discarded in favour to the first more simpler solution.
